name: Caddy Build Pipeline

on:
  workflow_dispatch:  # This enables the manual trigger

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out current repository and mount
        uses: actions/checkout@v3
        with:
          path: content

      - name: Use Parent Repository Workflow to Build Docker Image
        uses: draftm0de/kernel.deployment/.github/workflows/build-workflow.yml@main
        with:
          image: "draftm0de/kernel.caddy:latest"
          context: "/content/caddy"
          build_args: ".build_args"
