name: Caddy Build Pipeline

on:
  workflow_dispatch:  # This enables the manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
