name: Caddy Build Pipeline

on:
  workflow_dispatch:  # This enables the manual trigger

jobs: 
  build:
    uses: draftm0de/kernel.deployment/.github/workflows/build-workflow.yml@main
    with:
      namespace: "draftmode"
      image: "kernel.caddy"
      context: "caddy"
      build_args: ".build_args"
      tag_level: 3
      tag_base_version: ".version"
      protected_tag: "latest"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
