name: My Workflow

on:
  workflow_dispatch:  # This enables the manual trigger

jobs:
  build_image:
    uses: draftm0de/kernel.deployment/.github/workflows/build-workflow.yml@main
    with:
      context: "caddy"
      build_args: ".build_args"
