name: Caddy Build Pipeline

on:
  workflow_dispatch:  # This enables the manual trigger

jobs:
  build:
    uses: draftm0de/kernel.deployment/.github/workflows/build.yml@main
    with:
      image_namespace: "draftmode"
      image_name: "kernel.caddy"
      image_tag: "latest"
      # build_target:
      build_context: "caddy"
      build_args_file: ".build_args"
      artifact: "artifact"
      
#  push:
#    needs: build
#    uses: draftm0de/kernel.deployment/.github/workflows/push.yml@main
#    with:
#      image_namespace: "draftmode"
#      image_name: "kernel.caddy"
#      image_tag: "latest"
#      protect: true
#      artifact: "artifact"
#    secrets:
#      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

#  scan-trivy:
#    needs: build 
#    uses: draftm0de/kernel.deployment/.github/workflows/scan-trivy.yml@main
#    with:
#      image: "kernel.caddy"    
#      context: "caddy"
#      artifact_name: "artifact"
#      severity: "CRITICAL,HIGH" 
#      scanners: "vuln,secret,misconfig,license"
