name: Caddy Build Pipeline

on:
  workflow_dispatch:  # This enables the manual trigger

jobs: 
  build:
    uses: draftm0de/kernel.deployment/.github/workflows/build.yml@main
    with:
      namespace: "draftmode"
      image: "kernel.caddy"
      context: "caddy"
      build_args_file: ".build_args"
      artifact_name: "artifact"
      
  protection:
    needs: build
    uses: draftm0de/kernel.deployment/.github/workflows/sha-protection.yml@main
    with:
      image: "kernel.caddy"
      artifact_name: "artifact"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      
#  scan-trivy:
#    needs: build 
#    uses: draftm0de/kernel.deployment/.github/workflows/scan-trivy.yml@main
#    with:
#      image: "kernel.caddy"    
#      context: "caddy"
#      artifact_name: "artifact"
#      severity: "CRITICAL,HIGH" 
#      scanners: "vuln,secret,misconfig,license"
